baseurl = "https://blog.shaz.pw/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = true
  centerTheme = true
  favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "ShazPacc"
    subtitle = "Some Profound Shet ofc ofc"
    keywords = ""
    copyright = "©ShazPacc.inc (an actual company)"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "You want moar"

    [languages.en.params.logo]
      logoText = "ShazPacc"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "post"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
