on:
  push:
    branches:
      - main

jobs:
  UpdateServer:
    runs-on: self-hosted

    steps:
      - name: pull new changes from github
        run: cd ~/shazpacc/ && git pull origin main

      - name: run the updater script
        run: cd ~/shazpacc/ && hugo
      
      - name: restart nginx server
        run:  sudo systemctl restart nginx

