on:
  push:
    branches:
      - main

jobs:
  ServerUpdater:
    runs-on: self-hosted

    steps:
      - name: make updater script executable
        run: chmod +x ~/shazpacc/updateServer.sh

      - name: run the updater script
        run: ~/shazpacc/updateServer.sh
      
      - name: restart nginx server
        run:  sudo systemctl restart nginx

